config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/" => "users#input"
  post "output" => "users#output"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
  
  def input
    @user = User.all
  end
  
  def output
    @select_user = User.find_by(name: params[:name])
    @select_user.receiver = params[:receiver]
    @select_user.status = params[:status]
    @select_user.save
    redirect_to("/users")
    flash[:notice] = "お疲れさん、ありがとう！"
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :receiver, :status, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VariApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :receiver %>
    <%= form.text_field :receiver, id: :user_receiver %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :user_status %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :user_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Receiver</th>
      <th>Status</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.receiver %></td>
        <td><%= user.status %></td>
        <td><%= user.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to("続けて入力","/") %>

app/views/users/input.html.erb
<div class = "top">
    <div class = "container">
        <div class = "title">
        　　<h1>入力フォーム</h1>
        </div>
        <div class = "wrapper">
            <div class = "form">
              <%= form_tag("output", method: :post) do %>    
                <p>払った人</p>
                <select name="name">
                    <% @user.each do |user| %>
                    <option><%= user.name %></option>
                    <% end %>
                </select>
                <p>受け取った人</p>
                <select name="receiver">
                    <option value = "光希">光希</option>
                    <option value = "でくのぼう">でくのぼう</option>
                    <option value = "立川">立川</option>
                    <option value = "うんこ">うんこ</option>
                    <option value = "銀河">銀河</option>
                </select>
                <p>状況</p>
                <p>受け取った場合受取済み、いつまでに払うかを聞いた場合その日付を入力</p>
                　　<input name="status">
                <input value="送信" type="submit">
              <% end %>    
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @user.receiver %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Price:</strong>
  <%= @user.price %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>